name: VampireBats
main: me.bukkit.critikull.VampireBats.VampireBats
version: 1.1
author: Critikull
load: STARTUP
description: New VampireBat monsters
commands:
    vampirebats:
        description: VampireBats commands
        usage: /<command>
        aliases: [vamp]
permissions:
    critikull.vampirebats.reload:
        description: Use the reload command
        default: op
    critikull.vampirebats.debug:
        description: Use the debug command
        default: op
    critikull.vampirebats.spawn:
        description: Use the spawn command
        default: op